import { db } from '@/lib/db';
import { BaseAgent } from './base-agent';
import { getExecutionMode, persistAgentLog } from './agent-ai';
import {
  AgentRequest, AgentResult, AgentStatus, EvidenceType, AiUsageMetadata,
  ProductRequest, ProductResult, ProductConcept, MVPFeature, BuildPhase, EvidenceItem,
  ProductType, MonetizationModel,
} from './types';
import { v4 as uuidv4 } from 'uuid';
import { screenForHalalCompliance } from '@/lib/halal-filter';
import { generateValidated } from '@/lib/ai/generate';
import {
  PRODUCT_AI_SCHEMA,
  buildProductPrompt,
  buildMockProductOutput,
  normalizeProductAiOutput,
  ProductAiOutput,
} from '@/lib/ai/agent-prompts';

const VALID_PRODUCT_TYPES: ProductType[] = [
  'DIGITAL_PRODUCT', 'SAAS', 'WEB_APP', 'MOBILE_APP',
  'TEMPLATE', 'PRINTABLE', 'COURSE', 'TOOL', 'SERVICE_PRODUCT',
];

const VALID_MONETIZATION_MODELS: MonetizationModel[] = [
  'ONE_TIME_PURCHASE', 'SUBSCRIPTION', 'FREEMIUM',
  'SERVICE', 'LICENSE', 'AFFILIATE', 'AD_SUPPORTED',
];

const INFERENCE: EvidenceType = 'AI_INFERENCE';
const PURPOSE = 'product.concept';

/** Bounded, labelled context line for upstream agent output read from AgentLog. */
function summarizeAgentLogContext(
  agentType: string,
  log: { reasoning: string; evidenceType: string; fallbackUsed: boolean } | null
): { summary: string; evidenceType: EvidenceType } {
  if (!log) {
    return {
      summary: `No recorded ${agentType} agent execution is available for this opportunity.`,
      evidenceType: INFERENCE,
    };
  }
  const provenance = log.fallbackUsed
    ? `${agentType} context comes from a deterministic fallback (not live AI output)`
    : `${agentType} context is ${log.evidenceType}`;
  const text = (log.reasoning || '(no reasoning text recorded)').slice(0, 300);
  return {
    summary: `Last ${agentType} execution: ${text} [${provenance}]`,
    evidenceType: log.evidenceType === 'VERIFIED_DATA' ? 'VERIFIED_DATA' : INFERENCE,
  };
}

/** Load the latest research/validation AgentLog entries as upstream context. */
async function loadUpstreamContext(opportunityId?: string): Promise<{
  research: { summary: string; evidenceType: EvidenceType };
  validation: { summary: string; evidenceType: EvidenceType };
}> {
  const empty = {
    research: summarizeAgentLogContext('research', null),
    validation: summarizeAgentLogContext('validation', null),
  };
  try {
    const logs = await db.agentLog.findMany({
      where: {
        agentType: { in: ['research', 'validation'] },
        ...(opportunityId
          ? { input: { contains: opportunityId } }
          : {}),
      },
      orderBy: { createdAt: 'desc' },
      take: 20,
    });
    const latest = (type: string) =>
      logs.find((l) => l.agentType === type) ?? null;
    return {
      research: summarizeAgentLogContext('research', latest('research')),
      validation: summarizeAgentLogContext('validation', latest('validation')),
    };
  } catch (error) {
    console.error('Failed to load upstream agent context:', error);
    return empty;
  }
}

/**
 * Product Agent (Phase 4.2.3).
 *
 * Provider-agnostic by design: it never imports a concrete AI provider. Live
 * output flows through generateValidated() with the product purpose policy;
 * mock mode stays fully deterministic/offline; AI failures fail closed to a
 * clearly-labelled deterministic fallback — a failed AI call can NEVER be
 * re-labelled as VERIFIED_DATA or presented as live output. Research and
 * Validation context is loaded from AgentLog where available and preserved
 * with its original provenance.
 */
export class ProductAgent extends BaseAgent {
  constructor() {
    super({
      id: 'product-agent',
      type: 'product',
      name: 'Product Agent',
      description: 'Converts an eligible opportunity and its research/validation context into a structured product concept and build specification.',
      purpose: 'Generate structured product concepts, MVP specifications, build plans, and monetization hypotheses for opportunities that have sufficient research and validation context.',
      currentCapability:
        'Product workflow with real provider support behind the provider-agnostic generation layer. ' +
        'Structured product concepts, MVP specs, build plans, halal safety gates, provenance ' +
        '(AI_INFERENCE), research/validation context from AgentLog, and fail-closed fallback. ' +
        'Mock mode works fully offline; set AI_PROVIDER=gemini with a valid key for live calls.',
      status: 'MOCKED',
      evidencePolicy:
        'All product concepts, specifications, and plans generated by this agent are classified as AI_INFERENCE until verified by human or trusted data sources. ' +
        'User-entered fields are USER_ENTERED. VERIFIED_DATA only ever describes records read from the database. MOCKED marks deterministic fallback output.',
      safeExecutionState: true,
      icon: 'Package',
    });
  }

  private validateProductRequest(input: unknown): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    const req = input as Partial<ProductRequest>;

    if (!req.productObjective || typeof req.productObjective !== 'string' || req.productObjective.trim().length === 0) {
      errors.push('Valid product objective is required');
    }

    if (!req.productType || !VALID_PRODUCT_TYPES.includes(req.productType as ProductType)) {
      errors.push('productType must be one of: ' + VALID_PRODUCT_TYPES.join(', '));
    }

    if (req.opportunityId && typeof req.opportunityId !== 'string') {
      errors.push('opportunityId must be a string if provided');
    }

    if (req.targetAudience && typeof req.targetAudience !== 'string') {
      errors.push('targetAudience must be a string if provided');
    }

    if (req.customerProblem && typeof req.customerProblem !== 'string') {
      errors.push('customerProblem must be a string if provided');
    }

    if (req.preferredPlatform && typeof req.preferredPlatform !== 'string') {
      errors.push('preferredPlatform must be a string if provided');
    }

    if (req.constraints && !Array.isArray(req.constraints)) {
      errors.push('constraints must be an array if provided');
    }

    if (req.budgetConstraints && typeof req.budgetConstraints !== 'string') {
      errors.push('budgetConstraints must be a string if provided');
    }

    if (req.monetizationPreference && !VALID_MONETIZATION_MODELS.includes(req.monetizationPreference as MonetizationModel)) {
      errors.push('monetizationPreference must be one of: ' + VALID_MONETIZATION_MODELS.join(', '));
    }

    if (req.halalRequirements && !Array.isArray(req.halalRequirements)) {
      errors.push('halalRequirements must be an array if provided');
    }

    return { valid: errors.length === 0, errors };
  }

  private failure(message: string, error: string, executionTime: number): AgentResult {
    return {
      success: false,
      output: {},
      reasoning: message,
      evidenceType: INFERENCE,
      error,
      executionTime,
    };
  }

  async execute(request: AgentRequest): Promise<AgentResult> {
    const startTime = Date.now();
    const productRequest = request.input as unknown as ProductRequest;

    // 1. Input Validation
    const validation = this.validateProductRequest(productRequest);
    if (!validation.valid) {
      const errorMessage = 'Invalid product request: ' + validation.errors.join(', ');
      const result = this.failure(errorMessage, errorMessage, Date.now() - startTime);
      await this.logExecution(request.action, request.input, result);
      return result;
    }

    // 2. Opportunity Context Loading
    let opportunity: { id: string; title: string; problemSolved?: string; halalStatus: string; overallScore?: number; category: string; businessModel: string; monetizationMethod: string } | null = null;
    let opportunityHalalStatus: string | null = null;

    if (productRequest.opportunityId) {
      try {
        const foundOpportunity = await db.opportunity.findUnique({
          where: { id: productRequest.opportunityId },
        });

        if (!foundOpportunity) {
          const errorMessage = 'Opportunity with ID "' + productRequest.opportunityId + '" not found';
          const result = this.failure(errorMessage, errorMessage, Date.now() - startTime);
          await this.logExecution(request.action, request.input, result);
          return result;
        }

        opportunity = foundOpportunity;
        opportunityHalalStatus = foundOpportunity.halalStatus;
      } catch (dbError) {
        console.error('Database error details:', dbError);
        const errorMessage = 'Database error while loading opportunity';
        const result = this.failure(errorMessage, errorMessage, Date.now() - startTime);
        await this.logExecution(request.action, request.input, result);
        return result;
      }
    }

    // 3. Halal Safety Gates — deterministic, BEFORE any AI call. A NOT_ALLOWED
    // verdict returns here so the AI provider is NEVER invoked for prohibited work.
    let isBlocked = false;
    let humanReviewRequired = false;
    const halalConsiderations: string[] = [];

    if (opportunityHalalStatus === 'NOT_ALLOWED') {
      isBlocked = true;
      halalConsiderations.push('NOT_ALLOWED: This opportunity has been flagged as impermissible. Product creation plan is BLOCKED.');
    } else if (opportunityHalalStatus === 'REVIEW_REQUIRED') {
      humanReviewRequired = true;
      halalConsiderations.push('REVIEW_REQUIRED: This opportunity requires human review before proceeding.');
    } else if (opportunityHalalStatus === 'HALAL') {
      halalConsiderations.push('HALAL: Linked opportunity passed automated screening. This is a screening tool, not a religious authority.');
    }

    const halalScreen = screenForHalalCompliance(
      productRequest.productObjective,
      productRequest.customerProblem || '',
      opportunity?.category || 'Digital Products',
      opportunity?.businessModel || 'Direct Sales',
      productRequest.monetizationPreference || opportunity?.monetizationMethod || 'ONE_TIME_PURCHASE'
    );

    if (halalScreen.status === 'NOT_ALLOWED') {
      halalConsiderations.push('Product concept flagged: ' + halalScreen.reasons.join('; '));
      isBlocked = true;
    } else if (halalScreen.status === 'REVIEW_REQUIRED') {
      halalConsiderations.push('Product concept requires review: ' + halalScreen.reasons.join('; '));
      humanReviewRequired = true;
    }

    if (isBlocked) {
      const blockedResult: ProductResult = {
        productType: productRequest.productType,
        targetCustomer: productRequest.targetAudience || 'Not specified',
        problemBeingSolved: productRequest.customerProblem || 'Not specified',
        productConcept: {
          productNameHypothesis: 'BLOCKED — no product concept generated',
          oneLineDescription: 'Product concept generation is blocked by halal compliance screening.',
          customer: productRequest.targetAudience || 'Not specified',
          problem: productRequest.customerProblem || 'Not specified',
          proposedSolution: 'No solution is proposed. The underlying opportunity is NOT_ALLOWED.',
          coreValueProposition: 'None — execution is prohibited.',
          differentiationHypothesis: 'None — execution is prohibited.',
          productFormat: productRequest.productType.replace(/_/g, ' ').toLowerCase(),
          primaryUseCase: 'None — execution is prohibited.',
          evidenceType: INFERENCE,
        },
        valueProposition: 'None — execution is prohibited.',
        mvpFeatures: [],
        optionalFutureFeatures: [],
        userWorkflow: [],
        productRequirements: [],
        technicalRequirements: [],
        buildPhases: [],
        monetizationModel: productRequest.monetizationPreference || 'ONE_TIME_PURCHASE',
        monetizationRationale: 'No monetization rationale is produced for a blocked opportunity.',
        pricingHypothesis: 'No pricing hypothesis is produced for a blocked opportunity.',
        monetizationAssumptions: [],
        monetizationRisks: [],
        evidenceNeeded: [],
        distributionChannels: [],
        contentStrategy: 'No distribution/content strategy is produced for a blocked opportunity.',
        landingPageConcept: 'No landing page concept is produced for a blocked opportunity.',
        conversionPath: [],
        risks: ['NOT_ALLOWED: Product creation is blocked due to halal compliance failure.'],
        assumptions: [],
        evidence: halalConsiderations.map((c) => ({
          id: uuidv4(),
          type: INFERENCE,
          content: c,
          source: 'Halal safety gate',
        })),
        researchContext: 'Research context was not used: product generation is blocked.',
        validationContext: 'Validation context was not used: product generation is blocked.',
        confidence: 0,
        halalStatus: opportunityHalalStatus || halalScreen.status,
        humanReviewRequired: false,
        recommendation: 'BLOCKED: Product creation is NOT_ALLOWED for this opportunity. No execution recommendation is generated.',
        capabilityStatus: 'MOCKED',
      };

      const result: AgentResult = {
        success: false,
        output: blockedResult,
        reasoning: 'Product Agent blocked due to halal compliance checks. The AI provider was NOT called.',
        evidenceType: INFERENCE,
        error: 'Halal compliance check failed',
        fallbackUsed: false,
        executionTime: Date.now() - startTime,
      };
      await this.logExecution(request.action, request.input, result);
      return result;
    }

    // 4. Resolve execution mode. The NOT_ALLOWED branch above has already
    // returned, so the provider is never called for prohibited work.
    const mode = getExecutionMode();

    // 5. Load research/validation context from AgentLog (preserves provenance;
    // these are upstream AI inferences, never promoted to verified facts).
    const upstream = await loadUpstreamContext(productRequest.opportunityId);
    const researchContextSummary = upstream.research.summary;
    const validationContextSummary = upstream.validation.summary;

    // 6. Build the provider-agnostic prompt.
    const prompt = buildProductPrompt({
      productObjective: productRequest.productObjective,
      productType: productRequest.productType,
      targetAudience: productRequest.targetAudience,
      customerProblem: productRequest.customerProblem,
      preferredPlatform: productRequest.preferredPlatform,
      constraints: productRequest.constraints,
      budgetConstraints: productRequest.budgetConstraints,
      monetizationPreference: productRequest.monetizationPreference,
      halalRequirements: productRequest.halalRequirements,
      opportunity: opportunity
        ? {
            id: opportunity.id,
            title: opportunity.title,
            halalStatus: opportunity.halalStatus,
            category: opportunity.category,
            problemSolved: opportunity.problemSolved,
          }
        : null,
      halalConsiderations,
      researchContext: researchContextSummary,
      validationContext: validationContextSummary,
    });

    // 7. MOCKED path — deterministic, offline, no key/network required.
    if (mode.isMocked) {
      const mockOutput = buildMockProductOutput({
        productObjective: productRequest.productObjective,
        productType: productRequest.productType,
        targetAudience: productRequest.targetAudience,
        customerProblem: productRequest.customerProblem,
        preferredPlatform: productRequest.preferredPlatform,
        constraints: productRequest.constraints,
        budgetConstraints: productRequest.budgetConstraints,
        monetizationPreference: productRequest.monetizationPreference,
      });
      const output = this.buildProductResult({
        aiOutput: mockOutput,
        productRequest,
        opportunity,
        opportunityHalalStatus,
        halalConsiderations,
        humanReviewRequired,
        researchContext: researchContextSummary,
        validationContext: validationContextSummary,
        capabilityStatus: 'MOCKED',
        aiUsage: undefined,
        fallbackUsed: false,
      });
      const reasoning = humanReviewRequired
        ? 'Mock product completed, but findings require human review due to REVIEW_REQUIRED status.'
        : 'Mock product execution completed with a structured product specification. Real-world validation has NOT been performed.';
      const logId = await this.persistSingle(request, output, reasoning, 'MOCKED', undefined, false);

      return {
        success: true,
        output: { ...output, agentLogId: logId },
        reasoning,
        evidenceType: INFERENCE,
        capabilityStatus: 'MOCKED',
        fallbackUsed: false,
        executionTime: Date.now() - startTime,
      };
    }

    // 8. LIVE path — route through the generic AI generation layer. Model/token
    // policy comes from the purpose-specific policy inside generateValidated()
    // (including AI_MODEL_PRODUCT env overrides); no redundant overrides here.
    const outcome = await generateValidated<Record<string, unknown>>(
      prompt,
      PURPOSE,
      PRODUCT_AI_SCHEMA,
    );

    if (outcome.ok) {
      const aiOutput: ProductAiOutput = normalizeProductAiOutput(outcome.value);
      const aiUsage: AiUsageMetadata = {
        provider: outcome.usage.provider,
        model: outcome.usage.model,
        purpose: PURPOSE,
        inputTokens: outcome.usage.inputTokens,
        outputTokens: outcome.usage.outputTokens,
        estimatedCostUsd: outcome.usage.estimatedCostUsd,
        latencyMs: outcome.usage.latencyMs,
      };
      const output = this.buildProductResult({
        aiOutput,
        productRequest,
        opportunity,
        opportunityHalalStatus,
        halalConsiderations,
        humanReviewRequired,
        researchContext: researchContextSummary,
        validationContext: validationContextSummary,
        capabilityStatus: 'LIVE',
        aiUsage,
        fallbackUsed: false,
      });
      const reviewNote = humanReviewRequired ? ' Findings require human review (REVIEW_REQUIRED).' : '';
      const reasoning =
        `AI product specification completed via ${aiUsage.provider}/${aiUsage.model}; all output is AI_INFERENCE, not verified data.${reviewNote}`;
      const logId = await this.persistSingle(request, output, reasoning, 'LIVE', aiUsage, false);

      return {
        success: true,
        output: { ...output, agentLogId: logId },
        reasoning,
        evidenceType: INFERENCE,
        capabilityStatus: 'LIVE',
        aiUsage,
        fallbackUsed: false,
        executionTime: Date.now() - startTime,
      };
    }

    // 9. LIVE path failed closed: retries + repair could not produce schema-
    // valid output. Deterministic fallback is used and clearly marked — it is
    // NEVER presented as successful AI output and never VERIFIED_DATA.
    const fallbackOutput = buildMockProductOutput({
      productObjective: productRequest.productObjective,
      productType: productRequest.productType,
      targetAudience: productRequest.targetAudience,
      customerProblem: productRequest.customerProblem,
      preferredPlatform: productRequest.preferredPlatform,
      constraints: productRequest.constraints,
      budgetConstraints: productRequest.budgetConstraints,
      monetizationPreference: productRequest.monetizationPreference,
    });
    const output = this.buildProductResult({
      aiOutput: fallbackOutput,
      productRequest,
      opportunity,
      opportunityHalalStatus,
      halalConsiderations,
      humanReviewRequired,
      researchContext: researchContextSummary,
      validationContext: validationContextSummary,
      capabilityStatus: 'MOCKED',
      aiUsage: undefined,
      fallbackUsed: true,
      degraded: true,
    });
    const categories = (outcome.categories ?? []).join(', ') || 'unknown';
    const reasoning =
      `AI product generation failed after ${outcome.attempts} attempt(s) (categories: ${categories}). ` +
      'Deterministic fallback guidance is provided and clearly marked MOCKED; no live AI conclusions are included.';
    const logId = await this.persistSingle(request, output, reasoning, mode.capabilityStatus, undefined, true);

    return {
      success: false,
      output: { ...output, agentLogId: logId },
      reasoning,
      evidenceType: INFERENCE,
      capabilityStatus: mode.capabilityStatus,
      error: outcome.errors[0] ?? 'AI provider failed to produce valid structured output',
      fallbackUsed: true,
      executionTime: Date.now() - startTime,
    };
  }

  /** Persist exactly one AgentLog entry for this execution. */
  private async persistSingle(
    request: AgentRequest,
    output: ProductResult,
    reasoning: string,
    capabilityStatus: AgentStatus,
    aiUsage?: AiUsageMetadata,
    fallbackUsed = false,
  ): Promise<string | undefined> {
    const result: AgentResult = {
      success: true,
      output,
      reasoning,
      evidenceType: INFERENCE,
      executionTime: 0,
      capabilityStatus,
      ...(aiUsage ? { aiUsage, fallbackUsed } : { fallbackUsed }),
    };
    return persistAgentLog({ agentType: this.type, action: request.action, request, result });
  }

  private buildProductResult(input: {
    aiOutput: ProductAiOutput;
    productRequest: ProductRequest;
    opportunity: { id: string; title: string; problemSolved?: string; halalStatus: string; overallScore?: number; category: string; businessModel: string; monetizationMethod: string } | null;
    opportunityHalalStatus: string | null;
    halalConsiderations: string[];
    humanReviewRequired: boolean;
    researchContext: string;
    validationContext: string;
    capabilityStatus: 'LIVE' | 'MOCKED';
    aiUsage?: AiUsageMetadata;
    fallbackUsed: boolean;
    degraded?: boolean;
  }): ProductResult {
    const { aiOutput } = input;

    const productConcept: ProductConcept = {
      productNameHypothesis: aiOutput.productConcept.productNameHypothesis,
      oneLineDescription: aiOutput.productConcept.oneLineDescription,
      customer: aiOutput.productConcept.customer,
      problem: aiOutput.productConcept.problem,
      proposedSolution: aiOutput.productConcept.proposedSolution,
      coreValueProposition: aiOutput.productConcept.coreValueProposition,
      differentiationHypothesis: aiOutput.productConcept.differentiationHypothesis,
      productFormat: aiOutput.productConcept.productFormat,
      primaryUseCase: aiOutput.productConcept.primaryUseCase,
      evidenceType: INFERENCE,
    };

    const mvpFeatures: MVPFeature[] = aiOutput.mvpFeatures.map((f) => ({
      id: uuidv4(),
      name: f.name,
      description: f.description,
      priority: f.priority,
    }));

    const buildPhases: BuildPhase[] = aiOutput.buildPhases.map((p) => ({
      phase: p.phase,
      name: p.name,
      tasks: p.tasks,
      dependencies: p.dependencies,
      expectedOutput: p.expectedOutput,
      risk: p.risk,
    }));

    // Evidence provenance: everything derived from model output stays
    // AI_INFERENCE; user-entered fields are USER_ENTERED. AI output can NEVER
    // be promoted to VERIFIED_DATA here.
    const evidence: EvidenceItem[] = [
      {
        id: uuidv4(),
        type: INFERENCE,
        content: input.degraded
          ? 'Product specification generated by deterministic fallback after AI failure; clearly MOCKED, not live AI output.'
          : input.capabilityStatus === 'MOCKED'
            ? 'Product specification generated by the deterministic mock pipeline; clearly MOCKED, not live AI output.'
            : `Product specification generated via AI (${input.aiUsage?.provider ?? 'unknown'}/${input.aiUsage?.model ?? 'unknown'}); AI_INFERENCE, not verified data.`,
        source: 'Product Agent',
      },
      {
        id: uuidv4(),
        type: 'USER_ENTERED',
        content: 'User-provided product objective: ' + input.productRequest.productObjective,
        source: 'User input',
      },
    ];

    if (input.productRequest.targetAudience) {
      evidence.push({
        id: uuidv4(),
        type: 'USER_ENTERED',
        content: 'User-provided target audience: ' + input.productRequest.targetAudience,
        source: 'User input',
      });
    }
    if (input.productRequest.customerProblem) {
      evidence.push({
        id: uuidv4(),
        type: 'USER_ENTERED',
        content: 'User-provided customer problem: ' + input.productRequest.customerProblem,
        source: 'User input',
      });
    }
    if (input.opportunity) {
      evidence.push({
        id: uuidv4(),
        type: 'VERIFIED_DATA',
        content: `Opportunity loaded from database: "${input.opportunity.title}" (halal: ${input.opportunity.halalStatus}, score: ${input.opportunity.overallScore ?? 'n/a'})`,
        source: 'Prisma db.opportunity',
      });
    }
    for (const consideration of input.halalConsiderations) {
      evidence.push({
        id: uuidv4(),
        type: INFERENCE,
        content: consideration,
        source: 'Halal safety gate',
      });
    }
    if (input.aiUsage) {
      evidence.push({
        id: uuidv4(),
        type: INFERENCE,
        content: `AI usage: ${input.aiUsage.provider}/${input.aiUsage.model}, ${input.aiUsage.inputTokens} in / ${input.aiUsage.outputTokens} out tokens, estimated cost $${input.aiUsage.estimatedCostUsd.toFixed(6)} (estimate, not billing data).`,
        source: 'AI generation layer',
      });
    }
    evidence.push({
      id: uuidv4(),
      type: INFERENCE,
      content: 'Upstream research context: ' + input.researchContext,
      source: 'AgentLog (research agent)',
    });
    evidence.push({
      id: uuidv4(),
      type: INFERENCE,
      content: 'Upstream validation context: ' + input.validationContext,
      source: 'AgentLog (validation agent)',
    });

    let recommendation: string;
    if (input.humanReviewRequired) {
      recommendation = 'HUMAN REVIEW REQUIRED: Product specification generated but requires human review before any action. This product is NOT cleared for launch.';
    } else if (input.capabilityStatus === 'MOCKED') {
      recommendation = '[MOCKED] Product specification generated as a hypothesis. Real-world validation has NOT been performed. Human review required before any build or launch activity.';
    } else {
      recommendation = 'Product specification generated as AI inference. Real-world validation has NOT been performed. Human review required before any build or launch activity.';
    }

    return {
      opportunityContext: input.opportunity ? {
        id: input.opportunity.id,
        title: input.opportunity.title,
        problemSolved: input.opportunity.problemSolved,
        overallScore: input.opportunity.overallScore,
      } : undefined,
      productConcept,
      productType: input.productRequest.productType,
      targetCustomer: input.productRequest.targetAudience || aiOutput.productConcept.customer,
      problemBeingSolved: input.productRequest.customerProblem || aiOutput.productConcept.problem,
      valueProposition: productConcept.coreValueProposition,
      mvpFeatures,
      optionalFutureFeatures: aiOutput.optionalFutureFeatures,
      userWorkflow: aiOutput.userWorkflow,
      productRequirements: aiOutput.productRequirements,
      technicalRequirements: aiOutput.technicalRequirements,
      buildPhases,
      monetizationModel: aiOutput.monetizationModel,
      monetizationRationale: aiOutput.monetizationRationale,
      pricingHypothesis: aiOutput.pricingHypothesis,
      monetizationAssumptions: aiOutput.monetizationAssumptions,
      monetizationRisks: aiOutput.monetizationRisks,
      evidenceNeeded: aiOutput.evidenceNeeded,
      distributionChannels: aiOutput.distributionChannels,
      contentStrategy: aiOutput.contentStrategy,
      landingPageConcept: aiOutput.landingPageConcept,
      conversionPath: aiOutput.conversionPath,
      risks: aiOutput.risks,
      assumptions: aiOutput.assumptions,
      evidence,
      researchContext: input.researchContext,
      validationContext: input.validationContext,
      confidence: aiOutput.confidence,
      halalStatus: input.opportunityHalalStatus || 'HALAL',
      humanReviewRequired: input.humanReviewRequired,
      recommendation,
      capabilityStatus: input.capabilityStatus,
    };
  }
}
