import { db } from '@/lib/db';
import { BaseAgent } from './base-agent';
import {
  AgentRequest, AgentResult, AgentStatus, EvidenceType,
  ProductRequest, ProductResult, ProductConcept, MVPFeature, BuildPhase, EvidenceItem,
  ProductType, MonetizationModel,
} from './types';
import { v4 as uuidv4 } from 'uuid';
import { screenForHalalCompliance } from '@/lib/halal-filter';

const VALID_PRODUCT_TYPES: ProductType[] = [
  'DIGITAL_PRODUCT', 'SAAS', 'WEB_APP', 'MOBILE_APP',
  'TEMPLATE', 'PRINTABLE', 'COURSE', 'TOOL', 'SERVICE_PRODUCT',
];

const VALID_MONETIZATION_MODELS: MonetizationModel[] = [
  'ONE_TIME_PURCHASE', 'SUBSCRIPTION', 'FREEMIUM',
  'SERVICE', 'LICENSE', 'AFFILIATE', 'AD_SUPPORTED',
];

export class ProductAgent extends BaseAgent {
  constructor() {
    super({
      id: 'product-agent',
      type: 'product',
      name: 'Product Agent',
      description: 'Converts an eligible opportunity and its research/validation context into a structured product concept and build specification.',
      purpose: 'Generate structured product concepts, MVP specifications, build plans, and monetization hypotheses for opportunities that have sufficient research and validation context.',
      currentCapability: 'Mock product workflow fully implemented. Executes structured product requests with opportunity integration, halal safety checks, research/validation context preservation, and evidence classification. All results are mocked examples.',
      status: 'MOCKED',
      evidencePolicy: 'All product concepts, specifications, and plans generated by this agent are classified as AI_INFERENCE until verified by human or trusted data sources.',
      safeExecutionState: true,
      icon: 'Package',
    });
  }

  private validateProductRequest(input: unknown): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    const req = input as Partial<ProductRequest>;

    if (!req.productObjective || typeof req.productObjective !== "string" || req.productObjective.trim().length === 0) {
      errors.push("Valid product objective is required");
    }

    if (!req.productType || !VALID_PRODUCT_TYPES.includes(req.productType as ProductType)) {
      errors.push("productType must be one of: " + VALID_PRODUCT_TYPES.join(", "));
    }

    if (req.opportunityId && typeof req.opportunityId !== "string") {
      errors.push("opportunityId must be a string if provided");
    }

    if (req.targetAudience && typeof req.targetAudience !== "string") {
      errors.push("targetAudience must be a string if provided");
    }

    if (req.customerProblem && typeof req.customerProblem !== "string") {
      errors.push("customerProblem must be a string if provided");
    }

    if (req.preferredPlatform && typeof req.preferredPlatform !== "string") {
      errors.push("preferredPlatform must be a string if provided");
    }

    if (req.constraints && !Array.isArray(req.constraints)) {
      errors.push("constraints must be an array if provided");
    }

    if (req.budgetConstraints && typeof req.budgetConstraints !== "string") {
      errors.push("budgetConstraints must be a string if provided");
    }

    if (req.monetizationPreference && !VALID_MONETIZATION_MODELS.includes(req.monetizationPreference as MonetizationModel)) {
      errors.push("monetizationPreference must be one of: " + VALID_MONETIZATION_MODELS.join(", "));
    }

    if (req.halalRequirements && !Array.isArray(req.halalRequirements)) {
      errors.push("halalRequirements must be an array if provided");
    }

    return { valid: errors.length === 0, errors };
  }

  async execute(request: AgentRequest): Promise<AgentResult> {
    const startTime = Date.now();
    const productRequest = request.input as unknown as ProductRequest;

    // 1. Input Validation
    const validation = this.validateProductRequest(productRequest);
    if (!validation.valid) {
      const errorMessage = "Invalid product request: " + validation.errors.join(", ");
      const result: AgentResult = {
        success: false,
        output: {},
        reasoning: errorMessage,
        evidenceType: "AI_INFERENCE" as EvidenceType,
        error: errorMessage,
        executionTime: Date.now() - startTime,
      };
      await this.logExecution(request.action, request.input, result);
      return result;
    }

    // 2. Opportunity Context Loading
    let opportunity: { id: string; title: string; problemSolved?: string; halalStatus: string; overallScore?: number; category: string; businessModel: string; monetizationMethod: string } | null = null;
    let opportunityHalalStatus: string | null = null;
    let humanReviewRequired = false;
    let isBlocked = false;

    if (productRequest.opportunityId) {
      try {
        const foundOpportunity = await db.opportunity.findUnique({
          where: { id: productRequest.opportunityId },
        });

        if (!foundOpportunity) {
          const errorMessage = "Opportunity with ID \"" + productRequest.opportunityId + "\" not found";
          const result: AgentResult = {
            success: false,
            output: {},
            reasoning: errorMessage,
            evidenceType: "AI_INFERENCE" as EvidenceType,
            error: errorMessage,
            executionTime: Date.now() - startTime,
          };
          await this.logExecution(request.action, request.input, result);
          return result;
        }

        opportunity = foundOpportunity;
        opportunityHalalStatus = foundOpportunity.halalStatus;

        if (opportunityHalalStatus === "NOT_ALLOWED") {
          isBlocked = true;
        } else if (opportunityHalalStatus === "REVIEW_REQUIRED") {
          humanReviewRequired = true;
        }
      } catch (dbError) {
        console.error('Database error details:', dbError);

        const errorMessage = "Database error while loading opportunity";
        const result: AgentResult = {
          success: false,
          output: {},
          reasoning: errorMessage,
          evidenceType: "AI_INFERENCE" as EvidenceType,
          error: errorMessage,
          executionTime: Date.now() - startTime,
        };
        await this.logExecution(request.action, request.input, result);
        return result;
      }
    }
    // 3. Research + Validation Context Handling
    const hasResearchContext = false;
    const hasValidationContext = false;
    const researchContextSummary = hasResearchContext
      ? "Research context available for this opportunity."
      : "Insufficient verified evidence; product specification is based on hypotheses.";
    const validationContextSummary = hasValidationContext
      ? "Validation context available for this opportunity."
      : "Insufficient verified evidence; product specification is based on hypotheses.";

    // 4. Halal Safety Gate
    const halalConsiderations: string[] = [];

    if (opportunityHalalStatus === "NOT_ALLOWED") {
      halalConsiderations.push("NOT_ALLOWED: This opportunity has been flagged as impermissible. Product creation plan is BLOCKED.");
    } else if (opportunityHalalStatus === "REVIEW_REQUIRED") {
      halalConsiderations.push("REVIEW_REQUIRED: This opportunity requires human review before proceeding.");
    } else {
      halalConsiderations.push("HALAL: No compliance concerns identified by automated screening.");
    }

    const halalScreen = screenForHalalCompliance(
      productRequest.productObjective,
      productRequest.customerProblem || "",
      opportunity?.category || "Digital Products",
      opportunity?.businessModel || "Direct Sales",
      productRequest.monetizationPreference || opportunity?.monetizationMethod || "ONE_TIME_PURCHASE"
    );

    if (halalScreen.status === "NOT_ALLOWED") {
      halalConsiderations.push("Product concept flagged: " + halalScreen.reasons.join("; "));
      isBlocked = true;
    } else if (halalScreen.status === "REVIEW_REQUIRED") {
      halalConsiderations.push("Product concept requires review: " + halalScreen.reasons.join("; "));
      humanReviewRequired = true;
    }
    // 5. Product Concept Generation (AI_INFERENCE)
    const productTypeName = (productRequest.productType as string).replace(/_/g, " ").toLowerCase();
    const objectiveWords = productRequest.productObjective.split(" ").slice(0, 3).join(" ");

    const productConcept: ProductConcept = {
      productNameHypothesis: "[MOCKED] " + objectiveWords + " " + productTypeName + " Concept",
      oneLineDescription: "[MOCKED] A " + productTypeName + " designed to address: " + productRequest.productObjective,
      customer: productRequest.targetAudience || "[MOCKED] Target audience not specified",
      problem: productRequest.customerProblem || "[MOCKED] Customer problem not specified",
      proposedSolution: "[MOCKED] A " + productTypeName + " that provides a focused solution to the stated problem.",
      coreValueProposition: "[MOCKED] Hypothetical value: Solves the core problem with minimal friction and clear user benefit.",
      differentiationHypothesis: "[MOCKED] Differentiation is a hypothesis, not proven. Assumed differentiation based on focused approach to stated problem.",
      productFormat: productTypeName,
      primaryUseCase: "[MOCKED] Primary use case derived from product objective: " + productRequest.productObjective,
      evidenceType: "AI_INFERENCE" as EvidenceType,
    };

    // 6. MVP Specification
    const mvpFeatures: MVPFeature[] = [
      { id: uuidv4(), name: "Core Problem Resolution", description: "[MOCKED] The single most important feature that addresses: " + productRequest.productObjective, priority: "ESSENTIAL" },
      { id: uuidv4(), name: "User Authentication", description: "[MOCKED] Basic user registration and login functionality.", priority: "ESSENTIAL" },
      { id: uuidv4(), name: "Core Content/Delivery", description: "[MOCKED] The primary mechanism through which the " + productTypeName + " delivers value.", priority: "ESSENTIAL" },
      { id: uuidv4(), name: "Payment Integration", description: "[MOCKED] Basic payment processing for monetization.", priority: "IMPORTANT" },
      { id: uuidv4(), name: "Analytics and Tracking", description: "[MOCKED] Basic usage analytics to measure engagement and conversion.", priority: "IMPORTANT" },
      { id: uuidv4(), name: "Advanced Features", description: "[MOCKED] Additional features deferred beyond MVP.", priority: "DEFERRED" },
    ];

    const optionalFutureFeatures = [
      "[MOCKED] Advanced personalization and recommendation engine",
      "[MOCKED] Community features and user-generated content",
      "[MOCKED] Integration with third-party tools and services",
      "[MOCKED] Mobile application (if not already mobile)",
      "[MOCKED] Advanced analytics and reporting dashboard",
    ];

    const userWorkflow = [
      "[MOCKED] User discovers the product through distribution channel",
      "[MOCKED] User lands on landing page and reviews value proposition",
      "[MOCKED] User signs up or makes initial engagement",
      "[MOCKED] User experiences core product value",
      "[MOCKED] User completes purchase or conversion action",
      "[MOCKED] User receives product/access and onboarding",
    ];

    const productRequirements = [
      "[MOCKED] Must solve the stated problem: " + productRequest.productObjective,
      "[MOCKED] Must be usable by target audience without extensive training",
      "[MOCKED] Must support chosen monetization model",
      "[MOCKED] Must comply with halal requirements",
    ];

    if (productRequest.constraints && productRequest.constraints.length > 0) {
      productRequest.constraints.forEach(c => {
        productRequirements.push("[MOCKED] Constraint: " + c);
      });
    }

    const technicalRequirements = [
      "[MOCKED] Platform: " + (productRequest.preferredPlatform || "Web-based (default)"),
      "[MOCKED] Responsive design for multiple device types",
      "[MOCKED] Secure user data handling and privacy compliance",
      "[MOCKED] Scalable architecture to handle growth",
    ];

    if (productRequest.budgetConstraints) {
      technicalRequirements.push("[MOCKED] Budget constraint: " + productRequest.budgetConstraints);
    }
    // 7. Build Plan
    const buildPhases: BuildPhase[] = [
      {
        phase: 1, name: "Foundation",
        tasks: ["[MOCKED] Set up project repository and development environment", "[MOCKED] Define data models and database schema", "[MOCKED] Implement user authentication system", "[MOCKED] Create basic UI layout and navigation"],
        dependencies: [],
        expectedOutput: "Working development environment with auth and basic navigation",
        risk: "[MOCKED] Technical setup delays or dependency conflicts",
      },
      {
        phase: 2, name: "Core Functionality",
        tasks: ["[MOCKED] Implement core feature: " + (mvpFeatures[0]?.name || "Primary functionality"), "[MOCKED] Build content delivery mechanism", "[MOCKED] Implement payment processing", "[MOCKED] Create user dashboard and account management"],
        dependencies: ["Phase 1 completion"],
        expectedOutput: "Functional product with core value delivery working",
        risk: "[MOCKED] Core feature complexity may exceed initial estimates",
      },
      {
        phase: 3, name: "Testing and Polish",
        tasks: ["[MOCKED] Conduct user acceptance testing", "[MOCKED] Fix bugs and usability issues", "[MOCKED] Optimize performance and load times", "[MOCKED] Finalize content and copy"],
        dependencies: ["Phase 2 completion"],
        expectedOutput: "Polished product ready for launch preparation",
        risk: "[MOCKED] Testing may reveal fundamental issues requiring rework",
      },
      {
        phase: 4, name: "Launch Preparation",
        tasks: ["[MOCKED] Set up hosting and production environment", "[MOCKED] Create landing page and marketing materials", "[MOCKED] Configure analytics and tracking", "[MOCKED] Prepare launch checklist and rollback plan"],
        dependencies: ["Phase 3 completion"],
        expectedOutput: "Product deployed and ready for initial users",
        risk: "[MOCKED] Launch infrastructure issues or unexpected scaling needs",
      },
    ];
    // 8. Monetization Hypothesis
    const selectedMonetization: MonetizationModel | string = productRequest.monetizationPreference || "ONE_TIME_PURCHASE";
    const monetizationRationale = "[MOCKED] Hypothetical rationale: " + selectedMonetization + " model selected based on product type (" + productRequest.productType + ") and target audience. This is a hypothesis, not a proven model.";
    const pricingHypothesis = "[MOCKED] Pricing hypothesis: TBD based on market research and competitor analysis. No revenue claims are made.";
    const monetizationAssumptions = [
      "[MOCKED] Assumption: Target audience is willing to pay for this type of solution",
      "[MOCKED] Assumption: Price point will be competitive within the market",
      "[MOCKED] Assumption: Chosen monetization model fits the product format",
    ];
    const monetizationRisks = [
      "[MOCKED] Risk: Market may not accept the chosen price point",
      "[MOCKED] Risk: Monetization model may not generate sufficient revenue",
      "[MOCKED] Risk: Free alternatives may reduce willingness to pay",
    ];
    const evidenceNeeded = [
      "[MOCKED] Customer willingness-to-pay survey results",
      "[MOCKED] Competitor pricing analysis",
      "[MOCKED] Market size and revenue potential data",
      "[MOCKED] Conversion rate benchmarks for similar products",
    ];

    // 9. Distribution Hypothesis
    const distributionChannels = [
      "[MOCKED] Organic search (SEO) via content marketing",
      "[MOCKED] Social media presence on platforms where target audience is active",
      "[MOCKED] Direct outreach to potential customers",
    ];
    const contentStrategy = "[MOCKED] Content strategy hypothesis: Create educational content that addresses customer problems and demonstrates product value. No traffic or conversion claims are made.";
    const landingPageConcept = "[MOCKED] Landing page concept: Clear headline stating value proposition, problem agitation, solution presentation, social proof placeholder, and single call-to-action.";
    const conversionPath = [
      "[MOCKED] Visitor arrives at landing page",
      "[MOCKED] Visitor reads value proposition and problem statement",
      "[MOCKED] Visitor explores features and benefits",
      "[MOCKED] Visitor takes action (signup, purchase, or inquiry)",
      "[MOCKED] Visitor receives confirmation and onboarding",
    ];
    // 10. Risks and Assumptions
    const risks = isBlocked
      ? ["NOT_ALLOWED: Product creation is blocked due to halal compliance failure."]
      : humanReviewRequired
        ? ["REVIEW REQUIRED: All risks must be validated by human reviewer before proceeding."]
        : [
          "[MOCKED] Risk: Market demand may not materialize as hypothesized",
          "[MOCKED] Risk: Technical implementation may face unforeseen challenges",
          "[MOCKED] Risk: Competition may respond aggressively",
          "[MOCKED] Risk: Monetization model may not generate projected revenue",
        ];

    const assumptions = [
      "[MOCKED] Assumption: The stated customer problem is real and widespread enough to support a product",
      "[MOCKED] Assumption: Target audience can be reached through hypothesized channels",
      "[MOCKED] Assumption: The product can be built within stated constraints",
      "[MOCKED] Assumption: Monetization hypothesis will prove viable",
    ];

    // 11. Evidence - preserve provenance
    const evidence: EvidenceItem[] = [
      { id: uuidv4(), type: "AI_INFERENCE", content: "Product concept generated by AI based on provided opportunity and request parameters.", source: "Product Agent" },
      { id: uuidv4(), type: "USER_ENTERED", content: "User-provided product objective: " + productRequest.productObjective, source: "User input" },
    ];

    if (productRequest.targetAudience) {
      evidence.push({ id: uuidv4(), type: "USER_ENTERED", content: "User-provided target audience: " + productRequest.targetAudience, source: "User input" });
    }
    if (productRequest.customerProblem) {
      evidence.push({ id: uuidv4(), type: "USER_ENTERED", content: "User-provided customer problem: " + productRequest.customerProblem, source: "User input" });
    }

    // 12. Recommendation
    let recommendation: string;
    if (isBlocked) {
      recommendation = "BLOCKED: Product creation is NOT_ALLOWED for this opportunity. No execution recommendation is generated.";
    } else if (humanReviewRequired) {
      recommendation = "HUMAN REVIEW REQUIRED: Product specification generated but requires human review before any action. This product is NOT cleared for launch.";
    } else {
      recommendation = "[MOCKED] Product specification generated as a hypothesis. Real-world validation has NOT been performed. Human review required before any build or launch activity.";
    }
    // 13. Create final product result
    const finalProductResult: ProductResult = {
      opportunityContext: opportunity ? { id: opportunity.id, title: opportunity.title, problemSolved: opportunity.problemSolved, overallScore: opportunity.overallScore } : undefined,
      productConcept,
      productType: productRequest.productType,
      targetCustomer: productRequest.targetAudience || "[MOCKED] Target audience not specified",
      problemBeingSolved: productRequest.customerProblem || "[MOCKED] Customer problem not specified",
      valueProposition: productConcept.coreValueProposition,
      mvpFeatures,
      optionalFutureFeatures,
      userWorkflow,
      productRequirements,
      technicalRequirements,
      buildPhases,
      monetizationModel: selectedMonetization,
      monetizationRationale,
      pricingHypothesis,
      monetizationAssumptions,
      monetizationRisks,
      evidenceNeeded,
      distributionChannels,
      contentStrategy,
      landingPageConcept,
      conversionPath,
      risks,
      assumptions,
      evidence,
      researchContext: researchContextSummary,
      validationContext: validationContextSummary,
      confidence: isBlocked ? 0 : humanReviewRequired ? 0.45 : 0.5,
      halalStatus: opportunityHalalStatus || halalScreen.status,
      humanReviewRequired: isBlocked || humanReviewRequired,
      recommendation,
      capabilityStatus: this.status as AgentStatus,
    };

    // 14. Create AgentLog entry
    let agentLogId: string | undefined;
    try {
      const agentLog = await db.agentLog.create({
        data: {
          agentType: this.type,
          action: request.action,
          input: JSON.stringify(request.input),
          output: JSON.stringify(finalProductResult),
          reasoning: isBlocked
            ? "Product Agent blocked: opportunity is NOT_ALLOWED"
            : humanReviewRequired
              ? "Mock product completed, but findings require human review due to REVIEW_REQUIRED opportunity status"
              : "Mock product execution completed successfully with structured product specification",
          evidenceType: "AI_INFERENCE",
        },
      });
      agentLogId = agentLog.id;
      finalProductResult.agentLogId = agentLogId;
    } catch (logError) {
      console.error("Failed to log Product Agent execution: " + logError);
    }

    const finalResult: AgentResult = {
      success: true,
      output: finalProductResult,
      reasoning: isBlocked
        ? "Product Agent blocked: opportunity has NOT_ALLOWED halal status. No product specification generated."
        : humanReviewRequired
          ? "Mock product completed, but findings require human review due to REVIEW_REQUIRED opportunity status"
          : "Mock product execution completed successfully with structured product specification. Real-world product has NOT been built.",
      evidenceType: "AI_INFERENCE" as EvidenceType,
      executionTime: Date.now() - startTime,
    };

    return finalResult;
  }
}
