import { BaseAgent } from './base-agent';
import { AgentRequest, AgentResult, EvidenceType } from './types';

export class ProductAgent extends BaseAgent {
  constructor() {
    super({
      id: 'product-agent',
      type: 'product',
      name: 'Product Agent',
      description: 'Creates product plans and content. Generates outlines, descriptions, and production workflows.',
      purpose: 'Generate comprehensive product plans, content outlines, and production workflows for validated opportunities.',
      currentCapability: 'Architecture implemented. Live product planning capabilities coming in future phases. Currently returns mocked results only.',
      status: 'PLANNED',
      evidencePolicy: 'Product plans and content generated by this agent are classified as AI_INFERENCE and require human review before implementation.',
      safeExecutionState: true,
      icon: 'Package',
    });
  }

  async execute(request: AgentRequest): Promise<AgentResult> {
    // If opportunityId is provided, check halal compliance first
    if (request.input.opportunityHalalStatus) {
      const isSafe = this.validateHalalCompliance(request.input.opportunityHalalStatus as string);
      if (!isSafe) {
        return {
          success: false,
          output: {},
          reasoning: 'Cannot create product plan for this opportunity - it has failed halal compliance checks.',
          evidenceType: 'AI_INFERENCE' as EvidenceType,
          error: 'Halal compliance check failed',
          executionTime: 0,
        };
      }
    }

    // Return mocked result as live capabilities are not yet implemented
    const result = this.getMockResult(request);
    await this.logExecution(request.action, request.input, result);
    return result;
  }
}