// Phase 5.5 — Revenue ingestion API (live revenue recording).
//
// POST /api/revenue → record one VERIFIED revenue row with automatic
//                     attribution and idempotency. Revenue figures enter the
//                     system ONLY here (or via direct operator entry) — they
//                     are never generated by AI and never predicted.
//
// SECURITY MODEL (deliberate):
// - Write access requires OPERATOR_REVENUE_TOKEN from the server environment.
//   Without it the endpoint refuses with 503 — fail-closed, never open.
// - The token is compared with a length-safe constant-time comparison and is
//   never logged, never echoed, and never exposed to any AI call.
// - The idempotency key is derived server-side by the shared rule; the caller
//   cannot supply one, so replays collapse to DUPLICATE instead of
//   double-recorded revenue.
//
// Authentication is intentionally NOT username/password or a session here:
// this is an operator/automation endpoint, and the token must come from
// server-side configuration. If no token is configured, the honest answer is
// "not available" — never an open write path.

import { NextResponse } from 'next/server';
import { logger } from '@/lib/server-log';
import { recordRevenueWithAttribution } from '@/lib/product-factory/economics';
import { enforceRateLimit, clientIpFrom, readJsonBody, auditSecurityEvent } from '@/lib/security/guard';

export const dynamic = 'force-dynamic';

/** Length-safe constant-time string comparison (no early exit on mismatch). */
function tokensMatch(a: string, b: string): boolean {
  const aBytes = Buffer.from(a, 'utf8');
  const bBytes = Buffer.from(b, 'utf8');
  const lengthDelta = aBytes.length ^ bBytes.length;
  if (aBytes.length === 0 || bBytes.length === 0) return false;
  let diff = lengthDelta;
  const max = Math.max(aBytes.length, bBytes.length);
  for (let i = 0; i < max; i++) {
    diff |= (aBytes[i] ?? 0) ^ (bBytes[i] ?? 0);
  }
  return diff === 0;
}

export function verifyOperatorToken(presented: string | null): boolean {
  const expected = process.env.OPERATOR_REVENUE_TOKEN;
  if (!expected || expected.trim().length === 0) return false;
  if (!presented || presented.trim().length === 0) return false;
  return tokensMatch(expected.trim(), presented.trim());
}

export async function POST(request: Request) {
  const authHeader = request.headers.get('authorization');
  const presented = authHeader?.startsWith('Bearer ') ? authHeader.slice('Bearer '.length).trim() : null;

  // SECURITY: credential-guessing throttle. Keyed on the presented token (via
  // the shared rate limiter) so brute-force attempts are refused before the
  // constant-time comparison even runs; plus a coarse per-IP cap.
  const ip = clientIpFrom(request);
  const ipLimit = await enforceRateLimit({ surface: 'api:revenue:ip', identity: ip, max: 30, windowSeconds: 60 });
  if (!ipLimit.allowed) {
    await auditSecurityEvent({ kind: 'RATE_LIMITED', surface: 'api:revenue', outcome: 'refused' });
    return NextResponse.json({ ok: false, error: 'Rate limit exceeded. Retry later.' }, { status: 429 });
  }
  if (presented) {
    const tokenLimit = await enforceRateLimit({ surface: 'api:revenue:token', identity: presented, max: 20, windowSeconds: 60 });
    if (!tokenLimit.allowed) {
      await auditSecurityEvent({ kind: 'AUTH_FLOOD', surface: 'api:revenue', outcome: 'refused' });
      return NextResponse.json({ ok: false, error: 'Too many attempts. Retry later.' }, { status: 429 });
    }
  }

  if (!verifyOperatorToken(presented)) {
    const configured = Boolean(process.env.OPERATOR_REVENUE_TOKEN?.trim());
    await auditSecurityEvent({
      kind: 'AUTH_FAILURE',
      surface: 'api:revenue',
      outcome: 'refused',
      detail: configured ? 'bad-credential' : 'not-configured',
    });
    logger.warn('Revenue ingestion rejected', { reason: configured ? 'bad-token' : 'not-configured' });
    return NextResponse.json(
      {
        ok: false,
        error: configured
          ? 'Unauthorized: a valid operator token is required to record revenue.'
          : 'Revenue ingestion is NOT_CONFIGURED: set OPERATOR_REVENUE_TOKEN server-side to enable it. Nothing was recorded.',
      },
      { status: configured ? 401 : 503 },
    );
  }

  // Body: size-capped, strict-object, prototype-pollution-safe parse.
  const bodyGuard = await readJsonBody(request, { surface: 'api:revenue', maxBytes: 16 * 1024, maxChars: 8_000 });
  if (!bodyGuard.ok) {
    return NextResponse.json({ ok: false, error: bodyGuard.error }, { status: bodyGuard.status });
  }
  const raw = bodyGuard.value;
  const result = await recordRevenueWithAttribution({
    date: typeof raw.date === 'string' ? raw.date : '',
    revenueSource: typeof raw.revenueSource === 'string' ? raw.revenueSource : '',
    grossRevenue: typeof raw.grossRevenue === 'number' ? raw.grossRevenue : Number.NaN,
    fees: typeof raw.fees === 'number' ? raw.fees : undefined,
    netRevenue: typeof raw.netRevenue === 'number' ? raw.netRevenue : undefined,
    currency: typeof raw.currency === 'string' ? raw.currency : undefined,
    referenceNote: typeof raw.referenceNote === 'string' ? raw.referenceNote : undefined,
    productId: typeof raw.productId === 'string' ? raw.productId : null,
    opportunityId: typeof raw.opportunityId === 'string' ? raw.opportunityId : null,
  });

  if (result.status === 'INVALID') {
    return NextResponse.json({ ok: false, status: result.status, errors: result.errors }, { status: 400 });
  }
  return NextResponse.json(
    {
      ok: true,
      status: result.status,
      revenueId: result.revenueId,
      attribution: result.attribution,
    },
    { status: 200 },
  );
}
